api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "pc-builder-cart-transform"
type = "function"
uid = "337f1c31-5291-10b1-ec0f-30474b40fdae424da26f"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
